# Generated by Django 3.2.9 on 2021-11-18 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_socialmediapost'),
    ]

    operations = [
        migrations.CreateModel(
            name='Happy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.profile')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.socialmediapost')),
            ],
        ),
    ]
