# Generated by Django 3.2.9 on 2021-11-26 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('isOpen', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('min_experience', models.IntegerField(default=0)),
                ('max_experience', models.IntegerField(default=10)),
                ('salary_ctc', models.IntegerField()),
                ('age_limit', models.IntegerField(default=40)),
                ('isRemote', models.BooleanField(default=False)),
                ('category', models.ManyToManyField(related_name='job_category', to='api.JobCategory')),
                ('hirer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.profile')),
            ],
        ),
    ]
