# Generated by Django 3.2.9 on 2021-11-26 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_job_jobcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='company',
            field=models.CharField(default='NA', max_length=100),
            preserve_default=False,
        ),
    ]
